name: floor_demo
description: "Floor implementation on an Flutter app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  floor: ^1.4.0
  cached_network_image: ^3.2.3
  http: 1.2.0
  sqflite: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.1
  floor_generator: ^1.4.0
  build_runner: ^2.1.2

flutter:
  uses-material-design: true

